"""empty message

Revision ID: 388158565bbe
Revises: 8bf1576503fb
Create Date: 2023-11-13 01:51:36.591555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388158565bbe'
down_revision = '8bf1576503fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
